[INPUT]
# Root dir of downloaded CESM2 files on the test machine
input_root=./sample/CESM2/
model_name=CESM2
scenario=hist
esm_flag=r11i1p1f1
grid_flag=gn

[OUTPUT]
# ETL period: 2 x 6-hourly steps for smoke test
# YYYYMMDDHHMM
etl_strt_ts = 199001010000
etl_end_ts  = 199001020000
output_root = ./output/
